String file1="<!DOCTYPE html5>\n"
"\n"
"<html>\n"
"\n"
"<head>\n"
"<title>CONTROL PANEL</title>\n"
"</head>\n"
"\n"
"<script type=\"text/javascript\">\n"
"window.onload=Pinstatus;\n"
"function Pinstatus(){\n"
"morestatus();\n"
"}\n"
"\n"
"function morestatus(){\n"
"setTimeout(morestatus, 4000);\n"
"server = \"STATUS/99\";\n"
"request = new XMLHttpRequest();\n"
"request.onreadystatechange = updateasyncstatus;\n"
"request.open(\"GET\", server, true);\n"
"request.send(null);\n"
"}\n"
"function updateasyncstatus(){\n"
"if ((request.readyState == 4) && (request.status == 200))\n"
"{\n"
"result = request.responseText;\n"
"document.getElementById(\"description1\").innerHTML = result;\n"
"fullset = result.split(\"#\");\n"
"document.getElementById(\"description1\").innerHTML = fullset;\n"
"if(fullset[0]==\"STATUS\"){\n"
"document.getElementById(\"OutLuxId\").value=fullset[1];\n"
"document.getElementById(\"LightsWorking\").value=fullset[2];\n"
"}\n"
"}}\n"
"\n"
"\n"
"function ButtonClick(){\n"
"document.getElementById(\"description2\").innerHTML = \"Processing Status\";\n"
"server = document.getElementById(\"ModeId\").value+\"/\"+document.getElementById(\"TimeId\").value+\"/\"+document.getElementById(\"LuxId\").value;\n"
"request = new XMLHttpRequest();\n"
"request.onreadystatechange = UpdateStatus;\n"
"request.open(\"GET\", server, true);\n"
"request.send(null);\n"
"}\n"
"\n"
"function UpdateStatus(){\n"
"if ((request.readyState == 4) && (request.status == 200))\n"
"{\n"
"result = request.responseText;\n"
"document.getElementById(\"description2\").innerHTML = \"Present Status\"+result;\n"
"}\n"
"}\n"
"\n"
"\n"
"</script>\n"
"\n"
"<body bgcolor=\"#E69B84\">\n"
"\n"
"<table cellpadding=\"20\"  align=\"center\"  >\n"
"\n"
"<caption><h2>STREET LIGHT CONTROL PANEL</h2></caption>\n"
"\n"
"<tr>\n"
"<th align=\"center\" colspan=\"6\"   >SELECT MODE:</th>\n"
"<th><select id=\"ModeId\" name=\"Mode\" style=\"width: 100px;\">\n"
"  <option value=\"ON\">ON ALL</option>\n"
"  <option value=\"OFF\">OFF ALL</option>\n"
"  <option value=\"AUTO\">AUTO</option>\n"
"  <option value=\"SERIES_1\">SERIES_1</option>\n"
"  <option value=\"SERIES_2\">SERIES_2</option></select></th>\n"
"<th align=\"center\" colspan=\"6\"   >OUTDOOR LIGHT LUX:</th>\n"
"<th><input type=\"text\" style=\"text-align: center;\" style=\"width: 100px;\" name=\"analog\" id=\"OutLuxId\" value=\"0\" size=\"6\" readonly/></th>\n"
"</tr>\n"
"<tr>\n"
"<th align=\"center\" colspan=\"6\" >SELECT TIMER:</th>\n"
"<th><select id=\"TimeId\" name=\"Time\" style=\"width: 100px;\">\n"
"<option value=\"1\">1</option>\n"
"<option value=\"2\">2</option>\n"
"<option value=\"3\">3</option>\n"
"<option value=\"4\">4</option>\n"
"<option value=\"5\">5</option>\n"
"<option value=\"6\">6</option>\n"
"<option value=\"7\">7</option>\n"
"<option value=\"8\">8</option>\n"
"<option value=\"9\">9</option>\n"
"<option value=\"10\">10</option>\n"
"                        </select></th>\n"
"<th align=\"center\" colspan=\"6\" >LIGHTS WORKING:</th>\n"
"<th><input type=\"text\" style=\"text-align: center;\" style=\"width: 100px;\" name=\"analog\" id=\"LightsWorking\" value=\"0\" size=\"6\" readonly/></th>\n"
"</tr>\n"
"<tr>\n"
"<th align=\"center\" colspan=\"6\" >THRESHOLD LUX LEVEL:</th>\n"
"<th><select id=\"LuxId\" name=\"Lux\" style=\"width: 100px;\">\n"
"<option value=\"1\">1</option>\n"
"<option value=\"2\">2</option>\n"
"<option value=\"3\">3</option>\n"
"<option value=\"4\">4</option>\n"
"<option value=\"5\">5</option>\n"
"<option value=\"6\">6</option>\n"
"<option value=\"7\">7</option>\n"
"<option value=\"8\">8</option>\n"
"<option value=\"9\">9</option>\n"
"<option value=\"10\">10</option>\n"
"                        </select></th>\n"
"<th align=\"center\" colspan=\"6\" >FAULT LIGHTS:</th>\n"
"<th><input type=\"text\" style=\"text-align: center;\" style=\"width: 100px;\" name=\"analog\" id=\"FaultLights\" value=\"0\" size=\"6\" readonly/></th>\n"
"<th align=\"center\" colspan=\"6\" >VEHICLES PASSED:</th>\n"
"<th><input type=\"text\" style=\"text-align: center;\" style=\"width: 100px;\" name=\"analog1\" id=\"VehiclesPassed\" value=\"0\" size=\"6\" readonly/></th>\n"
"</tr>\n"
"\n"
"<th><button style=\"width: 100px;\"  align=\"center\" onclick=\"ButtonClick();\" >APPLY</button></th>\n"
"</table>\n"
"<p  id=\"description1\"> - </p>\n"
"<br>\n"
"<p  id=\"description2\"> - </p>\n"
"</body>\n"
"</html>";
